name: build-and-deploy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

on:
  push:
    branches:
      - devops

jobs:
  cdk:
    runs-on: ubuntu-latest
    steps:
    - name: clone the repo
      uses: actions/checkout@v1

    - name: cdk deploy
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'deploy'
        cdk_version: '1.125.0'
        working_dir: './cdk'


  deploy:
    runs-on: ubuntu-latest
    needs: cdk

    steps:
    - name: clone repo
      uses: actions/checkout@v1

    - name: install dependencies
      run: |
        npm install -g gatsby-cli
        npm install

    - name: build
      env:
        CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        MAILCHIMP_ENDPOINT: ${{ secrets.MAILCHIMP_ENDPOINT }}
      run: gatsby build

    - name: deploy to S3
      uses: reggionick/s3-deploy@v3
      with:
        folder: public
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
        dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
